variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

.default_job:
  image: docker:26
  services:
    - name: docker:26-dind

build-ui:
  stage: build
  extends: .default_job
  before_script:
    - docker info
  script:
    - docker build -f Dockerfile.ui -t myapp-ui:test .
    - docker save myapp-ui:test -o myapp-ui.tar
  artifacts:
    paths:
      - myapp-ui.tar
    expire_in: 1h
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

test-ui:
  stage: test
  extends: .default_job
  needs: ["build-ui"]
  script:
    - docker load -i myapp-ui.tar
    # Run container with a name, do not auto-remove (--rm)
    - set +e
    - docker run --name ui-tests myapp-ui:test python run.py
    - TEST_EXIT=$?
    - set -e
    # Copy reports/videos from container to job workspace
    - mkdir -p reports videos
    - docker cp ui-tests:/app/reports/. ./reports || true
    - docker cp ui-tests:/app/videos/. ./videos || true
    # Cleanup container
    - docker rm -f ui-tests || true
    # Return test exit code
    - exit $TEST_EXIT
  artifacts:
    when: always
    paths:
      - reports/
      - videos/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
